import { readFileSync, readdirSync } from 'node:fs';
import { basename, dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * That `components/ui` holds only what the application reaches.
 *
 * shadcn is installed here as a *behaviour* library, not a design system:
 * `globals.css` maps every one of its token names onto a Localize Infra token,
 * so a shadcn Sidebar renders in graphite and takes the Iris focus ring. That
 * bridge is deliberate and documented. What it does not do is stop the
 * directory filling up.
 *
 * It had eighteen components and reached seven. The other eleven — 1307 lines
 * — were generated by `npx shadcn add`, never imported, and nine of them
 * duplicated a primitive `packages/ui` already ships and tests: Badge, Table,
 * Tabs, Dialog, Breadcrumb, Avatar, Pagination, and the dropdown menu that is
 * `MenuRoot` here. Two, `collapsible` and `scroll-area`, had no counterpart and
 * no caller either.
 *
 * Unused code is not the real cost. The cost is that a reader looking for a
 * Badge finds two, one on the design system and one bypassing it, and the
 * import that is one character shorter is the wrong one. This repository has
 * already paid that bill: `isOperator` and `operatorInstallationId` had no
 * callers while three comments described them as what separated tenants.
 *
 * Deleting them is reversible in one command — `npx shadcn add <name>` — which
 * is exactly why keeping them cost more than removing them.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, '../..');

function sources(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return sources(path);
    if (!/\.tsx?$/.test(entry.name) || entry.name.includes('.test.')) return [];
    return [path];
  });
}

const FILES = sources(SRC).map((path) => ({
  path,
  posix: path.split(sep).join('/'),
  text: readFileSync(path, 'utf8'),
}));

/** The `@/components/ui/<name>` modules a file imports. */
function importsOf(text: string): string[] {
  return [...text.matchAll(/from '@\/components\/ui\/([a-z-]+)'/g)].map(
    (m) => m[1] as string,
  );
}

const present = FILES.filter((f) => f.posix.includes('/components/ui/'))
  .map((f) => basename(f.path, '.tsx'))
  .sort();

/**
 * Reached from application code, following imports through the directory.
 *
 * Transitive on purpose: `sidebar` pulls in `sheet`, `tooltip`, `skeleton`,
 * `button`, `input` and `separator`, none of which any page imports directly. A
 * check that only looked one hop out would call six of the seven dead and
 * delete the shell.
 */
function reachable(): Set<string> {
  const byName = new Map(
    FILES.filter((f) => f.posix.includes('/components/ui/')).map((f) => [
      basename(f.path, '.tsx'),
      f.text,
    ]),
  );
  const seen = new Set<string>();
  const queue = FILES.filter((f) => !f.posix.includes('/components/ui/'))
    .flatMap((f) => importsOf(f.text))
    .slice();
  while (queue.length > 0) {
    const name = queue.pop() as string;
    if (seen.has(name)) continue;
    seen.add(name);
    const text = byName.get(name);
    if (text) queue.push(...importsOf(text));
  }
  return seen;
}

describe('components/ui', () => {
  it('scans the source it is meant to guard', () => {
    // A moved directory would otherwise pass every assertion below by finding
    // nothing at all — the failure mode this repository keeps meeting.
    expect(FILES.length).toBeGreaterThan(40);
    expect(present.length).toBeGreaterThan(0);
  });

  it('holds nothing the application cannot reach', () => {
    const reached = reachable();
    expect(
      present.filter((name) => !reached.has(name)),
      'generated but never imported — delete it, or import it; `npx shadcn add <name>` brings it back',
    ).toEqual([]);
  });

  it('reaches only through the shell, not from pages', () => {
    /*
     * The one place shadcn is allowed to enter the application. Everything else
     * renders `packages/ui`, which is where the contract is enforced and where
     * the primitives are tested. A page importing `@/components/ui/*` directly
     * is the first step back to two design systems, and it is a one-line diff
     * that looks like nothing in review.
     */
    const ENTRY = [
      'src/app/layout.tsx',
      'src/components/app-sidebar.tsx',
      'src/components/app-topbar.tsx',
    ];
    const importers = FILES.filter(
      (f) =>
        !f.posix.includes('/components/ui/') && importsOf(f.text).length > 0,
    ).map((f) => f.posix.slice(f.posix.indexOf('src/')));
    expect(importers.sort()).toEqual([...ENTRY].sort());
  });
});
