-- Personal CLI tokens, one per person, revocable one at a time.
--
-- Until now `@localize-infra/cli` authenticated to the hosted API with the
-- operator's bearer token — one shared secret. Handing it out meant every
-- holder could translate on the operator's model account with no way to cut
-- one person off, and open pull requests through the operator's GitHub
-- installation on the repositories *it* reaches, the product's own included.
--
-- A token here belongs to a person *in a workspace*. The API resolves it to
-- that workspace and acts only through that workspace's own GitHub
-- installation.
--
-- Design decisions, each for a reason:
--
-- * **Only a hash is stored.** The plaintext is generated by the web server,
--   shown once, and never reaches this database: `token_hash` is SHA-256 of the
--   whole token. A leaked row does not leak a usable credential. The column is
--   not even readable by signed-in users (column grants below).
-- * **Every write goes through a definer function.** There are no insert,
--   update or delete policies, so the rules live in one place.
-- * **Tokens expire.** 90 days unless the creator picks otherwise, never more
--   than 366. A token that outlives anyone's memory of it is the one that leaks.
-- * **A token dies with its creator's membership.** Resolution checks that the
--   creator is still a member, so removing someone from a workspace revokes
--   their tokens without anyone remembering to.
-- * **Resolution is `service_role` only.** The API holds that key; nobody
--   signed in can ask "which workspace is this hash".
-- * **Guards are written NULL-safely.** `org_role(...) not in (...)` let
--   non-members through in link_github_installation (20260916000200); every
--   role check here tests for NULL first.

create table public.cli_tokens (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null
    references public.organizations (id) on delete cascade,
  created_by uuid references auth.users (id) on delete set null,

  name text not null check (length(btrim(name)) between 1 and 80),

  -- What a person sees to recognise a token: the scheme and six characters.
  token_prefix text not null check (token_prefix ~ '^lit_[A-Za-z0-9_-]{6}$'),
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),

  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_used_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid references auth.users (id) on delete set null,

  check (expires_at > created_at)
);

create index cli_tokens_organization_idx on public.cli_tokens (organization_id);

alter table public.cli_tokens enable row level security;

create policy cli_tokens_select_member
  on public.cli_tokens
  for select
  to authenticated
  using (public.is_org_member(organization_id));

-- Readable columns, and `token_hash` is not one of them.
revoke all on public.cli_tokens from anon, authenticated;
grant select (
  id, organization_id, created_by, name, token_prefix,
  created_at, expires_at, last_used_at, revoked_at, revoked_by
) on public.cli_tokens to authenticated;

-- Issue a token for the caller, in a workspace the caller belongs to.
create function public.create_cli_token(
  p_organization_id uuid,
  p_name text,
  p_token_hash text,
  p_token_prefix text,
  p_expires_at timestamptz default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller uuid := auth.uid();
  expiry timestamptz := coalesce(p_expires_at, now() + interval '90 days');
  active_count integer;
  created_id uuid;
begin
  if caller is null or not public.is_org_member(p_organization_id) then
    raise exception 'not a member of this workspace' using errcode = '42501';
  end if;

  if expiry <= now() or expiry > now() + interval '366 days' then
    raise exception 'a token must expire within a year' using errcode = '22023';
  end if;

  -- A ceiling, so a script or a compromised session cannot mint an unbounded
  -- number of credentials.
  select count(*) into active_count
    from public.cli_tokens t
   where t.organization_id = p_organization_id
     and t.created_by = caller
     and t.revoked_at is null
     and t.expires_at > now();
  if active_count >= 10 then
    raise exception 'you already have 10 active tokens in this workspace; revoke one first'
      using errcode = '54000';
  end if;

  insert into public.cli_tokens (
    organization_id, created_by, name, token_prefix, token_hash, expires_at
  )
  values (
    p_organization_id, caller, btrim(p_name), p_token_prefix, p_token_hash,
    expiry
  )
  returning id into created_id;

  return created_id;
end;
$$;

-- Revoke one token: its creator, or an owner or admin of its workspace.
create function public.revoke_cli_token(p_token_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller uuid := auth.uid();
  token public.cli_tokens;
  caller_role public.organization_role;
begin
  select * into token from public.cli_tokens where id = p_token_id;
  if token.id is null or caller is null then
    raise exception 'token not found' using errcode = '42704';
  end if;

  select m.role into caller_role
    from public.organization_members m
   where m.organization_id = token.organization_id
     and m.user_id = caller;

  -- Not a member at all: indistinguishable from a token that does not exist.
  if caller_role is null then
    raise exception 'token not found' using errcode = '42704';
  end if;

  if token.created_by is distinct from caller
     and caller_role not in ('owner', 'admin') then
    raise exception 'only the token''s creator or a workspace owner or admin can revoke it'
      using errcode = '42501';
  end if;

  update public.cli_tokens
     set revoked_at = coalesce(revoked_at, now()),
         revoked_by = coalesce(revoked_by, caller)
   where id = p_token_id;
end;
$$;

-- What the API asks for every request carrying a personal token.
create function public.resolve_cli_token(p_token_hash text)
returns table (
  token_id uuid,
  user_id uuid,
  organization_id uuid,
  organization_slug text,
  installation_id bigint,
  private_repositories boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  found_token public.cli_tokens;
begin
  select t.* into found_token
    from public.cli_tokens t
   where t.token_hash = p_token_hash
     and t.revoked_at is null
     and t.expires_at > now()
     and t.created_by is not null
     and exists (
       select 1 from public.organization_members m
        where m.organization_id = t.organization_id
          and m.user_id = t.created_by
     );

  if found_token.id is null then
    return;
  end if;

  update public.cli_tokens set last_used_at = now() where id = found_token.id;

  return query
    select found_token.id,
           found_token.created_by,
           o.id,
           o.slug,
           gi.installation_id,
           coalesce(e.private_repositories, false)
      from public.organizations o
      left join public.organization_github_installations gi
        on gi.organization_id = o.id
      left join public.organization_entitlements e
        on e.organization_id = o.id
     where o.id = found_token.organization_id;
end;
$$;

revoke execute on function
  public.create_cli_token(uuid, text, text, text, timestamptz)
  from public, anon;
revoke execute on function public.revoke_cli_token(uuid) from public, anon;
revoke execute on function public.resolve_cli_token(text)
  from public, anon, authenticated;

grant execute on function
  public.create_cli_token(uuid, text, text, text, timestamptz)
  to authenticated;
grant execute on function public.revoke_cli_token(uuid) to authenticated;
grant execute on function public.resolve_cli_token(text) to service_role;
