-- A run that had nothing to do, said explicitly.
--
-- The pipeline called /v1/open-pr unconditionally once the quality and
-- ambiguity gates passed. When every key was already translated, the files it
-- committed were unchanged from the branch under `catalogsEqual` — the
-- semantic equality that matters here, not a byte comparison of the files on
-- disk — so GitHub produced an empty commit and a pull request with zero
-- changed files. It produced five of them on the fixture repository in two
-- days, #10 through #14, all since closed. This comment first said "two such
-- pull requests are still open ... from August", meaning #1 and #2; both hold
-- real translations, and the claim had been copied without opening them.
--
-- A distinct status rather than `succeeded` with a null `pr_url`: those are two
-- different outcomes, and telling them apart by testing a nullable column for
-- null is exactly the kind of deduction this schema keeps removing. A reader —
-- the runs list, the activation funnel, a person — should not have to infer it.
--
-- Alone in its own migration. `alter type ... add value` and any statement that
-- *uses* the new value cannot share a transaction, and Supabase runs each
-- migration in one. Splitting removes the question entirely.
alter type public.run_status add value if not exists 'no_changes';
